// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARU5wUCvyv3sIBy2-Zka9F4HDCatpgHFU',
    appId: '1:2660035212:web:bc4109242050905d5169a9',
    messagingSenderId: '2660035212',
    projectId: 'fir-flutter-codelab-265b9',
    authDomain: 'fir-flutter-codelab-265b9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-265b9.appspot.com',
    measurementId: 'G-Y5WNWKRHQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11N5BcF1H39eThypagZqLNQIIJpqBwkg',
    appId: '1:2660035212:android:e7782c079ea71a535169a9',
    messagingSenderId: '2660035212',
    projectId: 'fir-flutter-codelab-265b9',
    storageBucket: 'fir-flutter-codelab-265b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hB9_oS4OTSCsc7UCpnS2vnpc8gZCtEM',
    appId: '1:2660035212:ios:a88ab3c9cd803f9e5169a9',
    messagingSenderId: '2660035212',
    projectId: 'fir-flutter-codelab-265b9',
    storageBucket: 'fir-flutter-codelab-265b9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4hB9_oS4OTSCsc7UCpnS2vnpc8gZCtEM',
    appId: '1:2660035212:ios:a88ab3c9cd803f9e5169a9',
    messagingSenderId: '2660035212',
    projectId: 'fir-flutter-codelab-265b9',
    storageBucket: 'fir-flutter-codelab-265b9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
